opentelemetry-collector:
  presets:
    kubernetesAttributes:
      enabled: true
    logsCollection:
      enabled: true

  config:
    processors:
      resourcedetection:
        detectors:
          - azure
          - env
          - eks
          - ec2
          - lambda
          - aks
          - system
        override: true
        timeout: 10s

    exporters:
      otlphttp/mezmologs:
        endpoint: "https://pipeline.use.dev.logdna.net/v1/7dc8f6b0-9640-11ee-b8ab-c23f77faa515"
        headers:
          Authorization: "4mRilGKGt1t8drJrJPaM8ZA7QFrZxcphwab7EtcD2gE="

    service:
      pipelines:
        logs:
          processors:
          - resourcedetection
          exporters:
            - otlphttp/mezmologs
            - logging
